### ISSUE TITLE
Heroku deployment error post migration

### ISSUE THREAD

**Issue by mikedonnici** [cardiacsociety/web-services#37]
After migrating the repository from mappcpd to cardiacsociety deployment from dev environment to Heroku failed: 

```
failed to set up sources from the following URLs:
ssh://git@github.com/cardiacsociety/web-services
: remote repository at ssh://git@github.com/cardiacsociety/web-services does not exist, or is inaccessible: Host key verification failed.
fatal: Could not read from remote repository.
```

Most likely this was because the repo was set to private. After setting back to public now get:

```
cmd/algr/directoryIndex.go:11:2: use of internal package not allowed
```

Heroku is attempting to deploy with Go 1.10.3.

First, check to see if internal package restriction was introduced in recent Go version.

Then, possible issue with `dep`...

**Comment by mikedonnici** [comment]
... issue was leftover `mappcpd` path in Gopkg.toml

```toml
[metadata.heroku]
  root-package = "github.com/mappcpd/web-services"
```

... which means the internal packages were not available.

changed to

```toml
[metadata.heroku]
  root-package = "github.com/cardiacsociety/web-services"
```

and all good.
